### PR TITLE
Bootstrap implementation to webpage

### PR DESCRIPTION
**Pull request by shuridbiswas**
Included Bootstrap Components from https://v4-alpha.getbootstrap.com/components/alerts/

- Buttons

- Navbar

- Card

Related to:

- Issue #3 

- Issue #13 

- Issue #16

### CODE REVIEW

**Comment by kevin-tan** [comment]
The html packag should be inside the frontend package, this way it will keep it more consistent

**Comment by ShawnGuerra-Bautista** [comment]
Actually, it should be

```
<dependency>
    <groupId>org.webjars</groupId>
    <artifactId>bootstrap</artifactId>
    <version>4.0.0</version>
</dependency>
```

**Comment by kevin-tan** [comment]
please update branch and remove bootstrap lib

**Comment by ShawnGuerra-Bautista** [comment]
Branch is too old; obsolete branch.

**Pull request closed without merging**
