### PR TITLE
Implementing Question Model and Vote Model

### PR DESCRIPTION
**Pull request by kevin-tan**
Added the following:
- JPA Repository for Questions to store and retrieve the object into the database
- QuestionController for front-end to retrieve question post data through REST end points
- Implemented Vote/Question/Answer Model

Related to:
- Issue #5 
- Issue #11

### CODE REVIEW

**Comment by SagarPatel43** [comment]
I am encountering errors when trying to test your implementation in Postman, please fix these before I take another look.

Also is it necessary for there to be two vote models (one for question/answer)? They're effectively the same when it comes to votes

**Comment by kevin-tan** [comment]
The fixes done to solve the issue with the HTTP request:
- The models did not have the annotation @JsonIgnore which will require the attributes in the body of the request. 
- The issue with a transient flush was caused because the model did not provide how the dependent field objects will be updated/created in the database (since they are all interconnected if you delete the model Question for example, the Answer model and Vote model should also be deleted in the database). To fix this we need to add parameters to the annotations @OneToMany, @OneToOne, etc, with a (cascade =Cascade.ALL) meaning delete/update every single related attributes off that main model in the databse.

**Comment by SagarPatel43** [comment]
Your implementation is now working, here are some comments I have:

- in the postQuestion method in QuestionController,there's no need to make another object when you already have one being passed in by @RequestBody

- When a question is edited we should know **when**, currently there is no implementation regarding "time of edit", only "time when posted"

**Comment by kevin-tan** [comment]
A follow up to the above point, all object/model references as a field are to have a @jsonignore and all primitive field types of an object/model that do not require to be provided in the json body are to be annotated with @jsonpropery(access = JsonPropert.Acess.READ_ONLY)

**Pull request merged**
