### PR TITLE
Added Role Feature

### PR DESCRIPTION
**Pull request by luca1030**

### CODE REVIEW

**Comment by kevin-tan** [comment]
Why is your branch broken?

**Comment by kevin-tan** [comment]
Remove the cascade on the ``Set<UserMode>`` in the RoleModel class and ``@JoinTable``, and define initialize the HashSet right away

**Comment by luca1030** [comment]
For some reason it creates to tables in the database. One callled role_model and one called role_model_users is this the  correct behavior?

**Comment by kevin-tan** [comment]
Could you update your branch with current changes?

**Comment by kevin-tan** [comment]
Yes it's normal since many user can reference many roles and many roles can reference many users

**Comment by kevin-tan** [comment]
Looks good you can merge it

**Pull request merged**
